### ISSUE TITLE
Confidence Algo : Support CSM in deploying confidence algo

### ISSUE THREAD

**Issue by aashutosh-samagra** [Konnect-Agri/tasks#31]

**Comment by Gautam-Rajeev** [comment]
Konnect needs a session with CSM and Silicon Tech Lab They wanted to understand how to go About deploying the confidence algo on Azure cloud system, so they'll have some queries regarding the same.
Need someone who knows deployment to also be in the call so as to answer deployment related queries. I can give a small half hour run-through on confidence algo to any DevOps engineer.

**Comment by karntrehan** [comment]
We will setup a KT call between @yuvrajsab and Karun. Karun will PS with CSM for Azure deployment

**Comment by aashutosh-samagra** [comment]
@karntrehan , we are planning to have a call with CSM on thursday (11th May) 11 am. Would be great if a call between Yuvraj and Karun is completed by tomorrow.

**Comment by karntrehan** [comment]
KT call between Karun and Yuvraj setup for today.
